project:
  type: website
  output-dir: docs

website:
  title: "Prasad Bhoite"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - Publications.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

